const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    TASKS_FETCHED: "TASKS_FETCHED",
    SET_RECOMMENDED_TASKS: "SET_RECOMMENDED_TASKS"
}

export default Constants;